---
baseurl: 'https://zhaohuabing.com'
title: Huabing Blog
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: zhaohuabings-blog
googleAnalytics: G-Q13FPWS6LW
preserveTaxonomyNames: true
paginate: 10
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
params:
  header_image: https://images.unsplash.com/34/BA1yLjNnQCI1yisIZGEi_2013-07-16_1922_IMG_9873.jpg?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80
  SEOTitle: 赵化冰的博客 | Zhaohuabing Blog
  description: '赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。'
  keyword: >-
    赵化冰, zhaohuabing, Zhaohuabing, , 赵化冰的网络日志, 赵化冰的博客, Zhaohuabing Blog, 博客,
    个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice
  slogan: I blog, therefore I am
  image_404: img/404-bg.jpg
  title_404: '你来到了没有知识的荒原 :('
  page_view_conter: false
  leancloud_app_id: Xu5MAnXL360Ms89vMVnWBjuq-gzGzoHsz
  leancloud_app_key: efUYEefAc2eIPBRO59PRERQC
  # https://forestry.io/blog/search-with-algolia-in-hugo/
  algolia_search: true
  algolia_appId: WM4BEY1UDN
  algolia_indexName: blog
  algolia_apiKey: 090c4a77b8bd4b8d2f2c1262afbc4be2
  sidebar_about_description: 'Engineer @Tencent Cloud, creator @Aeraki Mesh, open-source enthusiast, technical writer and life adventurer'
  sidebar_avatar: img/zhaohuabing-headshot-round-white.png
  featured_tags: true
  featured_condition_size: 5
  ba_track_id: a1d96090e4189c0376251fb043da7be5
  reward: false
  reward_guide: 嗯，这篇文章对我有用，鼓励一下...
  friends: false
  bookmarks: true
  about_me: true
  giscus:
    data_repo: zhaohuabing/zhaohuabing.github.io
    data_repo_id: MDEwOlJlcG9zaXRvcnkxMzc3MjcyMjM=
    data_category: Announcements
    data_category_id: DIC_kwDOCDWM984CAWAt
    data_mapping: pathname
    data_reactions_enabled: '1'
    data_emit_metadata: '0'
    data_theme: light
    data_lang: en
    crossorigin: anonymous

  # We need a proxy to access Disqus api in China
  disqus_proxy : 'https://disqusapi.zhaohuabing.com'
  disqus_site : 'https://zhaohuabing.com'
  social:
    rss: true
    email: zhaohuabing@zhaohuabing.com
    twitter: 'https://twitter.com/zhaohuabing'
    linkedin: 'https://www.linkedin.com/in/zhaohuabing'
    github: 'https://github.com/zhaohuabing'
    wechat: 'https://zhaohuabing.com/img/wechat_qrcode.jpg'
    medium: 'https://medium.com/@zhaohuabing'
  friend_link:
    - title: Linda的博客
      href: 'https://zhaozhihan.com'
    - title: Istio Operation Bible
      href: 'https://unsplash.com/'
  bookmark_link:
    - title: Aeraki Mesh
      href: 'https://aeraki.net/'
    - title: Istio 运维实战
      href: 'https://www.zhaohuabing.com/istio-guide'  
    - title: unsplash
      href: 'https://unsplash.com/'
    - title: pexels
      href: 'https://www.pexels.com'
    - title: excalidraw
      href: 'https://excalidraw.com/'
  publications:
    title: MY BOOKS
    items:
      - title: Distributed Tracing with Jaeger, Kubernetes, and Istio
        image: /img/liveproject.png
        href: https://www.manning.com/bundles/distributed-tracing-ser?utm_source=zhaohuabing&utm_medium=affiliate&utm_campaign=liveproject_zhao_distributed_9_7_21&a_aid=zhaohuabing&a_bid=ce8ffc93
      - title: 深入理解 Istio
        image: /img/2021-08-26-istio-handbook/book.jpeg
        href: https://www.zhaohuabing.com/post/2021-08-26-istio-handbook/
      - title: 云原生数据中心网络
        image: /img/cndc.png
        href: https://zhaohuabing.com/post/2021-08-27-cloud-native-data-center/
  addtional_menus:
    - title: ARCHIVE
      href: /archive/
    - title: NOTES
      href: /notes/
    - title: PHOTOS
      href: /photos/
    - title: READING
      href: /reading/ 
    - title: ABOUT
      href: /about/
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags
