[build]
[build.environment]
HUGO_VERSION = "0.96.0"
GO_VERSION = "1.18"
[[redirects]]
  from = "/learning-envoy/*"
  to = "https://hilarious-faloodeh-b9f59a.netlify.app/:splat"
  status = 200
  force = true

  
[[redirects]]
  from = "/learning-golang/*"
  to = "https://luxury-licorice-c5da80.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/learning-linux/*"
  to = "https://gilded-melomakarona-a91538.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/istio-guide/*"
  to = "https://istio-guide.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/web-slides/*"
  to = "https://web-slides.netlify.app/:splat"
  status = 200
  force = true